import { Video, Channel } from './types';

export const MOCK_CHANNELS: Channel[] = [
  { id: 'ch1', name: 'TechVision', avatar: 'https://picsum.photos/seed/tech/48/48', subscribers: 1230000 },
  { id: 'ch2', name: 'GamerGuild', avatar: 'https://picsum.photos/seed/game/48/48', subscribers: 4500000 },
  { id: 'ch3', name: 'VlogVentures', avatar: 'https://picsum.photos/seed/vlog/48/48', subscribers: 789000 },
  { id: 'ch4', name: 'MusicMakers', avatar: 'https://picsum.photos/seed/music/48/48', subscribers: 2100000 },
  { id: 'ch5', name: 'EduExplains', avatar: 'https://picsum.photos/seed/edu/48/48', subscribers: 950000 },
  { id: 'ch6', name: 'LiveNow', avatar: 'https://picsum.photos/seed/live/48/48', subscribers: 320000 },
];

export const SUBSCRIBED_CHANNELS_IDS = ['ch1', 'ch3', 'ch4']; // TechVision, VlogVentures, MusicMakers

export const CATEGORIES = ['All', 'Live Now', 'Subscriptions', 'Watch Later', 'Shorts', 'Education', 'Gaming', 'Live Events', 'Music', 'Tech', 'Vlogs'];


export const MOCK_VIDEOS: Video[] = [
  {
    id: 'vid1',
    title: 'The Future of AI: What to Expect in the Next 5 Years',
    thumbnail: 'https://picsum.photos/seed/ai/400/225',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    duration: '15:32',
    channel: MOCK_CHANNELS[0],
    views: '1.2M',
    uploadedAt: '2 weeks ago',
    description: `Join us as we dive deep into the advancements of Artificial Intelligence. From machine learning breakthroughs to ethical considerations, we cover what the next five years might hold for AI technology. \n\nFeaturing interviews with industry experts and live demos of cutting-edge AI.`,
    likes: 132000,
    dislikes: 1200,
    comments: [
      { id: 'c1', author: MOCK_CHANNELS[1], text: 'Incredible insights! The part about generative models was mind-blowing.', likes: 1500, replies: [], timestamp: '1 week ago'},
      { id: 'c2', author: MOCK_CHANNELS[4], text: 'Great overview. Could you do a follow-up on quantum computing?', likes: 800, replies: [], timestamp: '5 days ago'},
    ],
    isShort: false,
    category: 'Tech',
  },
  {
    id: 'vid2',
    title: 'Epic Gaming Moments Compilation #27',
    thumbnail: 'https://picsum.photos/seed/gaming/400/225',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    duration: '10:05',
    channel: MOCK_CHANNELS[1],
    views: '5.8M',
    uploadedAt: '3 days ago',
    description: 'The best and funniest gaming moments from the past week. Featuring clips from top streamers and our talented community. Submit your clips to be featured next!',
    likes: 450000,
    dislikes: 5000,
    comments: [],
    isShort: false,
    category: 'Gaming',
  },
  {
    id: 'short1',
    title: 'Satisfying Parkour Jump!',
    thumbnail: 'https://picsum.photos/seed/short1/225/400',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    duration: '0:15',
    channel: MOCK_CHANNELS[2],
    views: '12.1M',
    uploadedAt: '1 day ago',
    description: '#parkour #freerunning #shorts',
    likes: 1100000,
    dislikes: 2000,
    comments: [],
    isShort: true,
    category: 'Vlogs',
  },
  {
    id: 'vid3',
    title: 'Travel Vlog: Exploring the Alps',
    thumbnail: 'https://picsum.photos/seed/alps/400/225',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    duration: '22:10',
    channel: MOCK_CHANNELS[2],
    views: '540K',
    uploadedAt: '1 month ago',
    description: 'Our adventure through the Swiss Alps. Breathtaking views, challenging hikes, and amazing food. This is a trip we will never forget.',
    likes: 45000,
    dislikes: 300,
    comments: [],
    isShort: false,
    category: 'Vlogs',
  },
    {
    id: 'short2',
    title: 'This beat is 🔥',
    thumbnail: 'https://picsum.photos/seed/short2/225/400',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    duration: '0:30',
    channel: MOCK_CHANNELS[3],
    views: '8.9M',
    uploadedAt: '5 hours ago',
    description: 'New track dropping soon! #music #producer #shorts',
    likes: 890000,
    dislikes: 1500,
    comments: [],
    isShort: true,
    category: 'Music',
  },
  {
    id: 'vid4',
    title: 'Learn React in 60 Minutes',
    thumbnail: 'https://picsum.photos/seed/react/400/225',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    duration: '59:40',
    channel: MOCK_CHANNELS[4],
    views: '2.1M',
    uploadedAt: '6 months ago',
    description: 'A comprehensive tutorial for beginners to learn the fundamentals of React.js. We will build a simple application from scratch.',
    likes: 180000,
    dislikes: 2100,
    comments: [],
    isShort: false,
    category: 'Education',
  },
   {
    id: 'vid5',
    title: 'Lo-Fi Beats to Relax/Study to',
    thumbnail: 'https://picsum.photos/seed/lofi/400/225',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    duration: '2:30:00',
    channel: MOCK_CHANNELS[3],
    views: '150M',
    uploadedAt: '1 year ago',
    description: 'Chill beats for your daily activities. Enjoy the vibes.',
    likes: 2500000,
    dislikes: 10000,
    comments: [],
    isShort: false,
    category: 'Music',
  },
  {
    id: 'short3',
    title: 'Science experiment gone right!',
    thumbnail: 'https://picsum.photos/seed/short3/225/400',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    duration: '0:45',
    channel: MOCK_CHANNELS[4],
    views: '20.5M',
    uploadedAt: '3 days ago',
    description: 'You won\'t believe what happens next. #science #experiment #wow #shorts',
    likes: 2300000,
    dislikes: 4000,
    comments: [],
    isShort: true,
    category: 'Education',
  },
  {
    id: 'vid6',
    title: 'Live Concert: The Rockers Reunion Tour',
    thumbnail: 'https://picsum.photos/seed/liveevent/400/225',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    duration: '1:45:20',
    channel: MOCK_CHANNELS[5],
    views: '89K',
    uploadedAt: 'Streamed 2 days ago',
    description: 'Relive the epic moments from The Rockers Reunion Tour. Full concert recording.',
    likes: 12000,
    dislikes: 150,
    comments: [],
    isShort: false,
    category: 'Live Events',
  }
];