
import { GoogleGenAI, Type, Modality } from "@google/genai";

// Assume process.env.API_KEY is configured in the environment
const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  // This is a fallback for development environments where the key might not be set.
  // In a real production environment, this should not happen.
  console.warn("API_KEY is not set. AI features will be disabled.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY! });

interface VideoMetadata {
    title: string;
    description: string;
}

export const generateVideoMetadata = async (prompt: string): Promise<VideoMetadata> => {
    if (!API_KEY) {
        // Return mock data if API key is not available
        return new Promise(resolve => setTimeout(() => resolve({
            title: "AI Generated Title for: " + prompt,
            description: "This is a mock description generated by the AI because the API key is not available. The AI would normally create a detailed, engaging, and SEO-friendly description based on the prompt provided by the user."
        }), 1000));
    }
    
    try {
        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: `Based on the following video idea, generate a catchy, SEO-friendly title and a compelling video description. The description should be engaging and include relevant hashtags. Idea: "${prompt}"`,
            config: {
                responseMimeType: "application/json",
                responseSchema: {
                    type: Type.OBJECT,
                    properties: {
                        title: {
                            type: Type.STRING,
                            description: "The catchy video title, under 70 characters.",
                        },
                        description: {
                            type: Type.STRING,
                            description: "The engaging video description, around 150-200 words, ending with 3-5 relevant hashtags.",
                        },
                    },
                    required: ["title", "description"],
                },
            },
        });
        
        const jsonText = response.text.trim();
        const metadata = JSON.parse(jsonText);
        return metadata as VideoMetadata;

    } catch (error) {
        console.error("Error generating video metadata:", error);
        throw new Error("Failed to generate metadata from AI.");
    }
};

export const generateVideoThumbnail = async (prompt: string): Promise<string> => {
    if (!API_KEY) {
        // Return a placeholder if API key is not available
        return "https://picsum.photos/seed/ai-generated/400/225";
    }
    
    try {
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash-image',
            contents: {
                parts: [
                    {
                        text: `Generate a visually appealing and relevant thumbnail for a video with the following title and description. Focus on creating a simple, eye-catching image. Do not include any text in the image. Video details: ${prompt}`
                    },
                ],
            },
            config: {
                responseModalities: [Modality.IMAGE],
            },
        });

        for (const part of response.candidates[0].content.parts) {
            if (part.inlineData) {
                const base64ImageBytes: string = part.inlineData.data;
                return `data:image/png;base64,${base64ImageBytes}`;
            }
        }
        
        throw new Error("No image data found in AI response.");

    } catch (error) {
        console.error("Error generating video thumbnail:", error);
        throw new Error("Failed to generate thumbnail from AI.");
    }
};
